# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_window.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Competition(object):
    def setupUi(self, Competition):
        Competition.setObjectName("Competition")
        Competition.resize(1047, 585)
        Competition.setIconSize(QtCore.QSize(24, 24))
        Competition.setAnimated(False)
        self.centralwidget = QtWidgets.QWidget(Competition)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 130, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Caslon Pro Bold")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 170, 241, 151))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(400, 60, 91, 31))
        self.label_4.setObjectName("label_4")
        self.image_1 = QtWidgets.QLabel(self.centralwidget)
        self.image_1.setGeometry(QtCore.QRect(280, 110, 341, 291))
        self.image_1.setStyleSheet("")
        self.image_1.setText("")
        self.image_1.setObjectName("image_1")
        self.image_2 = QtWidgets.QLabel(self.centralwidget)
        self.image_2.setGeometry(QtCore.QRect(650, 110, 341, 291))
        self.image_2.setStyleSheet("")
        self.image_2.setText("")
        self.image_2.setObjectName("image_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(780, 60, 101, 31))
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(210, 30, 54, 12))
        self.label_2.setObjectName("label_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(280, 20, 601, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton_5 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton_5.setObjectName("radioButton_5")
        self.horizontalLayout.addWidget(self.radioButton_5)
        self.radioButton_4 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton_4.setObjectName("radioButton_4")
        self.horizontalLayout.addWidget(self.radioButton_4)
        self.radioButton_3 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout.addWidget(self.radioButton_3)
        self.radioButton_2 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout.addWidget(self.radioButton_2)
        self.radioButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout.addWidget(self.radioButton)
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(440, 430, 160, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(300, 430, 121, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(300, 460, 101, 16))
        self.label_7.setObjectName("label_7")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(440, 460, 160, 22))
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(300, 490, 111, 16))
        self.label_8.setObjectName("label_8")
        self.horizontalSlider_3 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_3.setGeometry(QtCore.QRect(440, 490, 160, 22))
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(630, 430, 41, 16))
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(630, 460, 41, 16))
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(630, 490, 41, 16))
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(950, 490, 75, 23))
        self.pushButton.setObjectName("pushButton")
        Competition.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Competition)
        self.statusbar.setObjectName("statusbar")
        Competition.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(Competition)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1047, 23))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        Competition.setMenuBar(self.menuBar)
        self.actionOpen_one_image_file = QtWidgets.QAction(Competition)
        self.actionOpen_one_image_file.setIconVisibleInMenu(True)
        self.actionOpen_one_image_file.setObjectName("actionOpen_one_image_file")
        self.actionExit = QtWidgets.QAction(Competition)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout_us = QtWidgets.QAction(Competition)
        self.actionAbout_us.setObjectName("actionAbout_us")
        self.actionVersion = QtWidgets.QAction(Competition)
        self.actionVersion.setObjectName("actionVersion")
        self.menu.addSeparator()
        self.menu.addAction(self.actionOpen_one_image_file)
        self.menu.addSeparator()
        self.menu.addAction(self.actionExit)
        self.menu.addSeparator()
        self.menu_2.addAction(self.actionAbout_us)
        self.menu_2.addAction(self.actionVersion)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())

        self.retranslateUi(Competition)
        QtCore.QMetaObject.connectSlotsByName(Competition)

    def retranslateUi(self, Competition):
        _translate = QtCore.QCoreApplication.translate
        Competition.setWindowTitle(_translate("Competition", "MainWindow"))
        self.label.setText(_translate("Competition", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#00007f;\">参赛学校：湖北文理学院</span></p></body></html>"))
        self.label_3.setText(_translate("Competition", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; color:#00007f;\">参赛队伍：湖文析影</span></p><p><span style=\" font-size:11pt; font-weight:600; color:#00007f;\">指导老师：朱丽娟，谢志远</span></p><p><span style=\" font-size:11pt; font-weight:600; color:#00007f;\">队长：王贤涛</span></p><p><span style=\" font-size:11pt; font-weight:600; color:#00007f;\">队员：杨兰兰，余雪银</span></p></body></html>"))
        self.label_4.setText(_translate("Competition", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">原始图像</span></p></body></html>"))
        self.label_5.setText(_translate("Competition", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">处理后得图像</span></p></body></html>"))
        self.label_2.setText(_translate("Competition", "选择距离："))
        self.radioButton_5.setText(_translate("Competition", "1cm"))
        self.radioButton_4.setText(_translate("Competition", "2cm"))
        self.radioButton_3.setText(_translate("Competition", "3cm"))
        self.radioButton_2.setText(_translate("Competition", "4cm"))
        self.radioButton.setText(_translate("Competition", "5cm"))
        self.label_6.setText(_translate("Competition", "图像预处理形态学调整"))
        self.label_7.setText(_translate("Competition", "定位大小调整"))
        self.label_8.setText(_translate("Competition", "输出图像形态学调整"))
        self.pushButton.setText(_translate("Competition", "保存图片"))
        self.menu.setTitle(_translate("Competition", "File"))
        self.menu_2.setTitle(_translate("Competition", "Help"))
        self.actionOpen_one_image_file.setText(_translate("Competition", "Open one image file"))
        self.actionOpen_one_image_file.setIconText(_translate("Competition", "Open one image file"))
        self.actionExit.setText(_translate("Competition", "Exit"))
        self.actionAbout_us.setText(_translate("Competition", "About us"))
        self.actionVersion.setText(_translate("Competition", "Version"))

